pipeline:

  build:
    image: php:7.1.11-fpm-alpine3.4
    commands:
      - apk update && apk add --no-cache git
      - sh tools/setup.sh
      - bin/phpspec run 

  fpm:
    image: plugins/ecr
    repo: 324044571751.dkr.ecr.us-east-1.amazonaws.com/engine
    registry: 324044571751.dkr.ecr.us-east-1.amazonaws.com
    secrets: [ ecr_access_key, ecr_secret_key ]
    dockerfile: containers/php-fpm/Dockerfile
    tags: fpm
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    when: 
      branch: [ master, test/codebuild ]

  runners:
    image: plugins/ecr
    repo: 324044571751.dkr.ecr.us-east-1.amazonaws.com/engine
    registry: 324044571751.dkr.ecr.us-east-1.amazonaws.com
    secrets: [ ecr_access_key, ecr_secret_key ]
    dockerfile: containers/php-runners/Dockerfile
    tags: runners
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    when: 
      branch: [ master, test/codebuild ]
